site_name: Documentation
repo_name: 'github.com/paycoreio'
repo_url: 'https://github.com/paycoreio/'
copyright: '© 2018 PayCore.io. All Rights Reserved.'
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo:
    icon: 'import_contacts'
  palette:
    primary: 'white'
    accent: 'white'
  feature:
    tabs: false
extra:
  social:
    - type: 'facebook'
      link: 'https://facebook.com/paycore.io/'
    - type: 'twitter'
      link: 'https://twitter.com/paycoreio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/paycore/'
    - type: 'github'
      link: 'https://github.com/paycoreio'
google_analytics:
  - 'UA-72023338-4'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
nav:
- Home: 'index.md'
- Payment gateway:
    - 'Overview': 'payment-gateway/overview.md'
- Payout gateway:
    - 'Overview': 'payout-gateway/overview.md'
- Currency rates:
    - 'Overview': 'currency-rates/overview.md'
- Release Notes: 'release-notes.md'