site_name: 'Documentation'
repo_name: 'paycoreio/docs'
repo_url: 'https://github.com/paycoreio/docs/'
copyright: '© 2018 PayCore.io. All Rights Reserved.'
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo:
    icon: 'import_contacts'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
extra:
  social:
    - type: 'facebook'
      link: 'https://facebook.com/paycore.io/'
    - type: 'twitter'
      link: 'https://twitter.com/paycoreio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/paycore/'
    - type: 'github'
      link: 'https://github.com/paycoreio'
  var1: 'test123'
google_analytics:
  - 'UA-72023338-4'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
- Home:
    - Introduction: 'index.md'
    - Release notes: 'release-notes.md'
- Getting started:
    - Overview: 'getting-started/overview.md'
    - User Profile: 
        - Overview: 'getting-started/user-profile/index.md'
        - General: 'getting-started/user-profile/general.md'
        - Security: 'getting-started/user-profile/security.md'
    - Organisation:
        - Overview: 'getting-started/organisation/index.md'
    - Public IPs: 'ips.md'
- Products:
    - Payment gateway:
        - Overview: 'products/payment-gateway/overview.md'
    - Payout gateway:
        - Overview: 'products/payout-gateway/overview.md'
    - Currency rates:
        - Overview: 'products/currency-rates/overview.md'
    - HPP:
        - Overview: 'products/hpp/overview.md'
- Providers: 
        - Overview: 'payment-providers/index.md'
        - Liqpay:
            - Connection manual: 'payment-providers/liqpay/connect-manual.md'
        - Advcash:
            - Connection manual: 'payment-providers/advcash/connect-manual.md'
        - CoinGate:
            - Connection manual: 'payment-providers/coingate/connect-manual.md'
        - 123x:
            - Connection manual: 'payment-providers/123xio/connect-manual.md'
        - Fondy:
            - Connection manual: 'payment-providers/fondy/connect-manual.md'
        - PayBox:
            - Connection manual: 'payment-providers/paybox/connect-manual.md'
        - Interkassa:
            - Connection manual: 'payment-providers/interkassa/connect-manual.md'
        - PayMega:
            - Connection manual: 'payment-providers/paymega/connect-manual.md'
        - AnyCash:  
            - Connection manual: 'payment-providers/anycash/connect-manual.md' 
        - 4bill: 
            - Connection manual: 'payment-providers/4billio/connect-manual.md'
        - ING Bank: 
            - Connection manual: 'payment-providers/ingbankpl/connect-manual.md'   
        - FlashPay: 
            - Connection manual: 'payment-providers/flashpay/connect-manual.md' 
        - Certus.Finance: 
            - Connection manual: 'payment-providers/certusfinance/connect-manual.md' 
        - GeoPay:
            - Connection manual: 'payment-providers/geopaynet/connect-manual.md' 
- Add-ons: 
    - Commerce:
        - Overview: 'commerce/overview.md'
    - Store:
        - Overview: 'store/overview.md'
    - Exchanger:
        - Overview: 'exchanger/overview.md'
