site_name: 'Documentation'
repo_name: 'github.com/paycoreio'
repo_url: 'https://github.com/paycoreio'
copyright: '© 2018 PayCore.io. All Rights Reserved.'
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo:
    icon: 'import_contacts'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
extra:
  social:
    - type: 'facebook'
      link: 'https://facebook.com/paycore.io/'
    - type: 'twitter'
      link: 'https://twitter.com/paycoreio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/paycore/'
    - type: 'github'
      link: 'https://github.com/paycoreio'
  var1: 'test123'
google_analytics:
  - 'UA-72023338-4'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
nav:
- Home:
    - Introduction: 'index.md'
    - Release Notes: 'release-notes.md'
- Getting started:
    - Overview: 'getting-started/overview.md'
    - Public IPs: 'getting-started/ips.md'
- Products:
    - Payment gateway:
        - Overview: 'products/payment-gateway/overview.md'
    - Payout gateway:
        - Overview: 'products/payout-gateway/overview.md'
    - Currency rates:
        - Overview: 'products/currency-rates/overview.md'
    - HPP:
        - Overview: 'products/hpp/overview.md'
- Providers: 
    - Page1: '#'
- Add-ons: 
    - Commerce:
        - Overview: 'commerce/overview.md'
    - Store:
        - Overview: 'store/overview.md'
    - Exchanger:
        - Overview: 'exchanger/overview.md'